Cesta p©es hory je velmi zt¡‘en  t¡m, ‘e v tˆchto hor ch se
usadily divok‚ Harpyje a zarytˆ br n¡ svoje £zem¡. Velmi £‡innˆ
jim v tom pom haj¡ Orkov‚, kte©¡ vˆd¡, ‘e tu jde o mnoho.
P©edpokl d  se tu velmi siln˜ odpor. Jedinou mo‘nost¡ jak
oslabit protivn¡kovy ©ady o Harpyje, je odst©elit ‡ sti skaln¡ho
masivu a zatarasit alespo¤ na ‡as vchody do jeskyn¡. Speci lnˆ
kv–li t‚to misi dorazily dvˆ roty samohybn˜ch minomet– M106.