 Je to z hada. Na tomto £zem¡ nejsou ‘ dn¡ nep© tel‚, jen
mˆste‡ko pln‚ na smrt vystra¨en˜ch obyvatel, p©ibli‘nˆ t˜den
od©¡znut˜ch od svˆta.
 Osadn¡ci s hr–zou hovo©¡ o nˆjak‚m m¡stˆ, kde se kdysi ve
st©edovˆku konala velk  bitva, po jej¡m‘ skon‡en¡ tam pochovaly
sv‚ mrtv‚ obˆ znep© telen‚ strany. Nyn¡ se zd , ‘e mrtv¡
vst vaj¡ ze sv˜ch hrob– a ohro‘uj¡ p©ev ‘nˆ v noci obyvatele
mˆste‡ka. Prvn¡ pohled ni‡emu takov‚mu nenasvˆd‡oval. Proto byla
tato hrozba vylou‡ena jako neopodstatnˆn . Snad i proto pohled
na mrtv‚ vst vaj¡c¡ z hrob– a £to‡¡c¡ na n s n mi ot© sl tak
mocnˆ. Ale u‘ je pozdˆ. Mus¡me se br nit. A to pr vˆ uprost©ed
hlubok‚ noci.
