Kdy‘ se na¨e jednotky p©ibl¡‘ily na dohled, naskytla se jim
scen‚rie boje mezi Mri a pavoukoidn¡mi bytostmi. Pr vˆ
p©ich zela Ka-Orksk  pˆchota a s n¡ se na obzoru objevila
obrovit  silueta s kapuc¡. V tom okam‘iku, kdy‘  ji bytosti
zahl‚dly,  v hr–ze padly na zem a boj byl u konce. Silueta
autoritativnˆ promluvila a potom se rozplynula v povˆt©¡.
V¨echny doposavad znep© telen‚ odd¡ly se oto‡ily smˆrem k 
na¨im vojsk–m a pustily se do £toku.

