Shrom ‘dily se tu odd¡ly, kter‚ se z©ejmˆ po por ‘k ch
Arachnoid– rozhodly ustoupit na m¡sta se zabezpe‡enou obranou. 
Mo‘n  by se jim poda©ilo ustoupit nepozorovanˆ. Ale nepo‡¡taly 
se satelitn¡m monitoringem, kter˜ zachytil jejich pohyb a umo‘nil 
n ¨ proti£tok. Je nutn‚ £to‡it, kdy‘ jsou zraniteln¡ - na voln‚m 
prostranstv¡. Potom m–‘e b˜t u‘ pozdˆ. Toto je pr vˆ ta operace, 
kter  m–‘e potvrdit d–vˆru Gener ln¡ho ¨t bu ve va¨e schopnosti.

Vyu‘ili jsme moci a v˜hod, kter˜ch jsme dos hli uveden¡m
¨pion ‘n¡ho satelitu do provozu a monitorov n¡m £zem¡. Podle
p©edbˆ‘n˜ch odhad– je tu o nˆco v¡ce ne‘ t©icet jednotek, mezi
nimi i mechanick‚ vˆ‘e ‡i Golemov‚. Vel¡ jim zku¨en¡ kouzeln¡ci.
—zem¡ se rychle zapl¤uje mlhou, z©ejmˆ Other Side nˆkdo varoval.
S na¨¡ vnit©n¡ infiltrac¡ budeme muset urychlenˆ nˆco udˆlat.
V¨echno poukazuje na zradu uvnit© nejvy¨¨¡ho velen¡.

