Jak se dalo o‡ek vat. Je tu velmi siln  skupina nep©¡tele. Snad
a‘ p©¡li¨ siln  vzhledem k tomu, jak m lo mˆl vˆdˆt nep©¡tel o
na¨¡ snaze. Nˆkdo musel Other Side varovat, o co tu jde. Jinak
si to mno‘stv¡ siln˜ch a zku¨en˜ch odd¡l– nen¡ mo‘n‚ vysvˆtlit.
Science Troop nedorazila v‡as a my mus¡me celou oblast udr‘et
pod kontrolou, do t‚ doby, dokud bude hrozit nebezpe‡¡ destrukce
za©¡zen¡. Jestli‘e se n m nepoda©¡ £zem¡ v‡as dob˜t, p©ijdou
siln‚ nep© telsk‚ posily.

