Abychom dostali pod kontrolu tuto oblast, mus¡me zni‡it port ly,
kter‚ zabezpe‡uj¡ zdej¨¡m odd¡l–m neust l˜ p©¡sun posil. Ale
hlavn¡m c¡lem je zab¡t nep© telsk‚ho gener la. Mus¡me se prob¡t
pod silnou nep© telskou palbou do pevnosti a gener la p©ipravit
o ‘ivot. Nejen‘e jeho smrt¡ p©iprav¡me P na br ny Dragotha o
siln‚ho spojence, ale uvedeme ve zmatek tak‚ v¨echny nep© telsk‚
odd¡ly na tomto £zem¡. Jejich odpor potom lehce zlom¡me.