Mus¡me se za ka‘dou cenu dostat a‘ k magick‚ Br nˆ, kter  vede
na Other Side. Velitelstv¡ po‡¡t  s t¡m, ‘e jakmile se k n¡
dostaneme, mus¡me se j¡ pokusit zni‡it z d lky. Ale jak p©esnˆ
Br na vypad , ani ‘ dn‚ dal¨¡ podrobnosti n m nen¡ nikdo schopen
ozn mit. Jdeme na slepo. A to je v boji s takov˜m velk˜m vl dcem, 
jak˜m je Dragoth, a nav¡c v boji o samotn˜ z kladn¡ k men jeho 
moci smrtelnˆ nebezpe‡n‚. Spole‡nˆ s draky a jeho vybran˜mi Orky 
Krvav‚ho plamene zde proti n m stoj¡ neskute‡n  moc. A to se 
nepo‡¡t  se situac¡, ‘e by Dragoth mohl p©ivolat z Br ny dal¨¡ 
posily p©¡mo z Other Side. Douf me, ‘e k tomu nedojde i proto, 
‘e n m nic jin‚ho ne‘ doufat nezb˜v .