Tak‘e hodina H je tu. Odd¡ly Aliance p©ekro‡ily bojov‚ linie a
ocitly se pod p©¡mou palbou fanatik– z Other Side. Mnoz¡ ze 
sp© telen˜ch Ork– pronikli a‘ do hloubky nep© telsk˜ch lini¡. 
Podkop vaj¡ autoritu Zahalen˜ch m g– a podnˆcuj¡ nespokojenost 
s Ka-Orky. Z posledn¡ch zpr v od Ka-Tugragov˜ch Ork– v¡me, ‘e 
odd¡ly jsou na pokraji vzpoury. Ale dokud jsou tu p©¡tomni 
Dragothovi kouzeln¡ci a draci, nezv¡tˆz¡me. Dal¨¡m c¡lem je 
zni‡it port ly, proto‘e neust le hroz¡ nebezpe‡¡ p©¡chodu posil 
od jin˜ch P n– bran. Mus¡me zv¡tˆzit. Mus¡me zni‡it Dragotha 
za ka‘dou cenu.