Lidsk‚ oko je¨tˆ nikdy p©edt¡m nevidˆlo pohromadˆ takov‚
obrovsk‚ vojsko. Tis¡ce besti¡ a nejr–znˆj¨¡ch kreatur. ›iky
bytost¡ jsou odhodl ny br nit svoji hrozivou vl dkyni a z ©¡c¡
artefakt Br ny. Rozhoduj¡c¡ boj za‡¡n . Teƒ se rozhodne.
Nyn¡ kone‡nˆ dok ‘eme ocenit satelitn¡ navigaci. Shora se
spou¨tˆj¡ bombard‚ry a s ƒ belsk˜m ©evem bombami trhaj¡ Medusiny
odd¡ly na kusy. Ale od mnoh˜ch pilot– jsme zachytili vol n¡ o
pomoc, kter‚ odum¡ralo v bolesti. Co to tam ta proklet  Medusa
vyvolala? V ka‘d‚m p©¡padˆ odd¡ly nep© tel po© dnˆ pro©¡dly.

