P©i¨li jsme k jeskyni, kterou ozna‡ili na¨i zvˆdov‚ a
senzibilov‚ Sboru PARE za zdroj nezn m‚ energie. Narazili jsme
na str ‘, kter  nepat©¡ k Other Side. Odpor nep© tel se
koncentruje okolo vchodu. Tak‚ tyto kon‡iny maj¡ sv‚ str ‘ce.
Ale podle senzibil– existuje je¨tˆ jedno takov‚to £zem¡ Abychom
mohli rozlu¨tit h danku s pr–chodem k artefaktu, mus¡ b˜t obˆ
dvˆ na¨e. —to‡¡ na n s str ‘ci kopce! A potom se z ni‡eho nic
zhmotnila vedla na¨ich odd¡l– stra¨n  bestie, podobn  t‚, se
kterou jsme se setkali v posledn¡ bitvˆ s Medusou. Podle zvˆd–
ten stra¨n˜ Br‚orn p©ich z¡ z mal‚ho neposkvrnˆn‚ho h jku, do
kter‚ho jsme neopatrnˆ vkro‡ili.

