Mus¡me dostat jednotku s Temnome‡em k Tit novi a zab¡t ho. To
jedin‚ jej zastav¡. Jenom‘e Murdanurovy hordy jsou proti Tit novˆ
zhoubn‚ moci chr nˆny a br n¡ n m v cestˆ k nˆmu. Nesmrteln  
bytost zat¡m nem  dost sil k pohybu. Ale Murdanur mu dod v  dal¨¡ 
a dal¨¡ s¡ly.

Dorazili sem KA - Tugragovy elitn¡ odd¡ly. S m orksk˜ gener l
prohl sil, ‘e jsou p©ipraveni zou‡astnit se z vˆre‡n˜ch operac¡.
Nevˆ©¡ sice, ‘e zv¡tˆz¡me, ale tak nebo tak, by jej i jeho Orky
‡ekala stra¨n  smrt. Apokalypsa je zase o krok bl¡‘e.